<h2>Vítejte v administraci, jste přihlášeni jako <?= $jmeno ?></h2>
<h3>Rychlé předvolby pro úpravu Pojištěncu a jejich pojištění</h3>
<?php if (!$admin) : ?>
    <p>Nemáte administrátorská oprávnění, požádejte administrátora webu, aby vám je přidělil.</p>
<?php endif ?>
<h2><a href="editor"></a></h2>

<h4>Poslední 3 přidané pojistky</h4>
<?php if ($admin) : ?>
    <a href="vlozitpoj">
        <button type="button" class="btn btn-secondary btn-lg btn-block">Nové pojištění</button>
    </a>
<?php endif ?>
<table class="table table-hover">

    <tr class="table-info">
        <th>Název pojištění</th>
        <th>Předmět pojistění</th>
        <th>Akce</th>
    </tr>

    <?php foreach ($pojisteni as $pojistka) : ?>

        <tr>

            <td>
                <a href="pojisteni/<?= htmlspecialchars($pojistka['id_pojisteni']) ?>"><?= htmlspecialchars($pojistka['nazev']) ?></a>
            </td>

            <td><?= htmlspecialchars($pojistka['predmet']) ?></td>
            <?php if ($admin) : ?>
                <td>
                    <button type="button" class="btn btn-outline-secondary"><a
                                href="editorpoj/<?= $pojistka['id_pojisteni'] ?>">Editovat</a></button>
                    <button type="button" class="btn btn-outline-secondary"><a
                                href="pojisteni/<?= $pojistka['id_pojisteni'] ?>/odstranit">Odstranit</a></button>

                </td>
            <?php endif ?>
        </tr>

    <?php endforeach ?>
</table>
<h4>Poslední 3 přidaní uživatelé</h4>
<?php if ($admin) : ?>
    <a href="vlozitpoj/<?= htmlspecialchars($id_pojistence) ?>">
        <button type="button" class="btn btn-secondary btn-lg btn-block">Nové pojištění</button>
    </a>
<?php endif ?>
<table class="table table-hover">

    <tr class="table-info">
        <th>Jméno Přijmení</th>
        <th>Bydliště</th>
        <th>Akce</th>

    </tr>
    <?php foreach ($pojistenci as $pojistnik) : ?>

        <tr>
            <td>
                <a href="pojistenci/<?= htmlspecialchars($pojistnik['id_pojistence']) ?>"><?= htmlspecialchars($pojistnik['jmeno']) . ' ' . htmlspecialchars($pojistnik['prijmeni']) ?></a>
            </td>

            <td><?= htmlspecialchars($pojistnik['ulice']) . ', ' . htmlspecialchars($pojistnik['mesto']) . ', ' . htmlspecialchars($pojistnik['psc']) ?></td>

            <?php if ($admin) : ?>
                <td>
                    <button type="button" class="btn btn-outline-secondary"><a
                                href="editor/<?= $pojistnik['id_pojistence'] ?>">Editovat</a></button>
                    <button type="button" class="btn btn-outline-secondary">
                        <a href="pojisteni/<?= $pojistnik['id_pojistence'] ?>/odstranit">Odstranit</a>
                    </button>

                </td>
            <?php endif ?>
        </tr>

    <?php endforeach ?>
</table>
