<h1>Seznam Pojištěných osob</h1>
<table class="tabulka">

<tr>
        <th>Jmeno Přijmení</th>
        <th>bydliště</th>
        <th>Akce</th>
		
		
    </tr>
    <?php foreach ($pojistenci as $pojistnik) : ?>

        <tr>
            <td><a href="pojistenci/<?= htmlspecialchars($pojistnik['id_pojistence']) ?>"><?= htmlspecialchars($pojistnik['jmeno']) . ' ' . htmlspecialchars($pojistnik['prijmeni']) ?></a></td>
          
            <td><?=htmlspecialchars($pojistnik['ulice']) . ', ' . htmlspecialchars($pojistnik['mesto']) . ', ' . htmlspecialchars($pojistnik['psc']) ?></td>
            <td><a href="editor">Editovat</a> <a href="Smazat">Smazat</a></td>
			
			
        </tr>

    <?php endforeach ?>
</table>
