<header>
    <h1><?= htmlspecialchars($jmeno) ?> <?= htmlspecialchars($prijmeni) ?></h1>
</header>
<section>
    <table class="tabulka">
    <tr>
    <td><?= htmlspecialchars($ulice) ?></td>
    <td><?= htmlspecialchars($email) ?></td>
    </tr>
    <tr>
    <td><?= htmlspecialchars($mesto) ?></td>
    <td><?= htmlspecialchars($telefon) ?></td>
    </tr>
    <tr>
    <td><?= htmlspecialchars($psc) ?></td>
    </tr>
</table>
</section>
