<header>
    <h1><?= htmlspecialchars($nazev)?></h1>
</header>
<section>
    <table class="table">
        <tr>
            <td><?= htmlspecialchars($castka) ?></td>

        </tr>
        <tr>

            <td><?= htmlspecialchars($predmet) ?></td>
        </tr>
        <tr>
            <td><?= htmlspecialchars($platnost_od) ?></td>
            <td><?= htmlspecialchars($platnost_do) ?></td>
        </tr>
    </table>