<h1>Zde se můžete zaregistrovat</h1>

<form method="post">
    Jméno<br />
    <input class="form-control" type="text" name="jmeno" /><br />
    Heslo<br />
    <input  class="form-control" type="password" name="heslo" /><br />
    Heslo znovu<br />
    <input class="form-control" type="password" name="heslo_znovu" /><br />
    Zadejte aktuální Rok (antispam)<br />
    <input class="form-control" type="int" name="rok" /><br />
    <input  type="submit" value="Registrovat" /><br />
</form>