<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localhost" />
        <meta charset="UTF-8" />
        <title>WEB</title>
        <meta name="description" content="web" />
        <meta name="keywords" content="web" />
        <link rel="stylesheet" href="style.css" type="text/css"/>
    </head>

    <body>
        <header>
            <h1>ITnetworkMVC - ukázkový web</h1>
        </header>
                <?php foreach ($zpravy as $zprava) : ?>
                    <p class="zprava"><?= $zpravy ?></p>
                <?php endforeach ?>    
        <nav>
            <ul>
                <li><a href="stranka">Hlavní stránka</a></li>
                <li><a href="pojistenci">Pojištěnci</a></li>
                <li><a href="kontakt">Kontakt</a></li>
                <li><a href="prihlaseni">Přihlásit</a></li>
                <li><a href="registrace">Zaregistrovat</a></li>
            </ul>
        </nav>
        <br clear="both" />

        <article>
            <?php $this->kontroler->vypisPohled(); ?>
        </article>

        <footer>
        Vytvořil &copy;Michael Eret jako finální projekt ke zkoušce pro <a href="https://itnetwork.cz">itnetwork.cz</a>
    </footer>
    </body>
</html>
