<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localhost" />
        <meta charset="UTF-8" />
        <title>WEB</title>
        <meta name="description" content="web" />
        <meta name="keywords" content="web" />

        <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">

        <script src="js/dashboard.js">

        </script>



        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
            }

            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                    font-size: 3.5rem;
                }
            }

            .b-example-divider {
                height: 3rem;
                background-color: rgba(0, 0, 0, .1);
                border: solid rgba(0, 0, 0, .15);
                border-width: 1px 0;
                box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
            }

            .b-example-vr {
                flex-shrink: 0;
                width: 1.5rem;
                height: 100vh;
            }

            .bi {
                vertical-align: -.125em;
                fill: currentColor;
            }

            .nav-scroller {
                position: relative;
                z-index: 2;
                height: 2.75rem;
                overflow-y: hidden;
            }

            .nav-scroller .nav {
                display: flex;
                flex-wrap: nowrap;
                padding-bottom: 1rem;
                margin-top: -1px;
                overflow-x: auto;
                text-align: center;
                white-space: nowrap;
                -webkit-overflow-scrolling: touch;
            }
        </style>
        <link rel="stylesheet" href="css/nav/dashboard.css">
    </head>

    <body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="stranka">Mik-PRO</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-nav">
            <div class="nav-item text-nowrap">

                <?php if(isset($_SESSION['uzivatel'])) :?>
                    <a class="nav-link px-3" href="administrace">Administrace</a>
                <a class="nav-link px-3" href="administrace/odhlasit">Odhlásit</a>
                <?php else: ?>
                    <div>
                    <a class="nav-link px-3" href="prihlaseni">Přihlášení</a>
                    </div>
                    <div class="nav-item text-nowrap">
                        <a class="nav-link px-3" href="registrace">Registrace</a>
                    </div>
                <?php endif?>
            </div>

        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-2 col-lg-2 d-md-block bg-light ">
                <div class="position-sticky pt-3 sidebar-sticky">
                    <ul class="nav flex-column">

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"  href="stranka">
                                <span class="align-text-bottom"></span>
                                Hlavní
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="pojistenci">
                                <span class="align-text-bottom"></span>
                                Pojištenci
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="pojisteni">
                                <span class="align-text-bottom"></span>
                                Pojištění
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="kontakt">
                                <span class="align-text-bottom"></span>
                                O Aplikaci...
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

                <div class="table-responsive">
                <?php /** @var TYPE_NAME $zpravy */
                foreach ($zpravy as $zprava) : ?>
                <div class="alert alert-warning" role="alert">
                        <p class="zprava"><?= $zprava ?></p>
                    </div>

                <?php endforeach ?>


                    <?php $this->kontroler->vypisPohled(); ?>

                </div>
            </main>
        </div>
    </div>
        <footer class="footer mt-auto py-3 bg-light">
            <div class="container">
                Vytvořil &copy;Michael Eret jako finální projekt ke zkoušce pro <a href="https://itnetwork.cz">itnetwork.cz</a>
            </div>
        </footer>


    </body>
</html>
